import { Providers } from './providers';
import type { Metadata } from 'next';
import Header from './_components/Header';

export const metadata: Metadata = {
  title: "Reddit Video Games Feed",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  return (
    <html lang="en">
      <Header />
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
